[project]
name = "sbom-generator"
version = "0.1.0"
description = "sbom-generator: A FastAPI application to generate Software Bill of Materials (SBOM) from various programming language dependency files."
readme = "README.md"
authors = [
  { name = "madhunaidu", email = "madhu.namburi@opsmx.io" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]==0.115.13",
    "uvicorn==0.38.0",
    "pydantic==2.11.7",
    "requests==2.32.5",
    "python-multipart==0.0.20",
    "python-dotenv==1.1.0",
    "toml==0.10.2",
    "uv~=0.9"
]

[tool.setuptools]
packages = ["go_sbom", "maven_sbom", "python_sbom"]

[tool.uv]
# Optional: You can configure uv-specific settings here
